### ISSUE TITLE
Installation Script for OpenSuse Leap

### ISSUE THREAD

**Issue by wrighematthey** [fastSimulations/fastExtendSetup#1]
Is it possible to modify the installation script to work with OpenSuse Leap 42.1?  I have tried to use the existing scripts but, whilst they do not generate obvious errors, the installation does not work properly.

**Comment by fastSimulations** [comment]
We'll need to determine where the failure point has happened, I've just completed a clean install of Leap 42.1 and used both scripts successfully.  So to diagnose your installation let's start with the following:

1) Remove the foam directory, /home/USER/foam
2) Execute the following on the command line from the fastExtendSetup directory:
    sh fastfcOpenSuseSetup.sh > fastfcOSSetup.log 2>&1
3) Exectue the following on the command line from the fastExtendSetup directory:
    sh fastfcExtendSetupPatching.sh > fastfcExtendSP.log 2>&1
4) Upload the two output files, fastfcOSSetup.log and fastfcExtendSP.log

I will review the logs and see if there are any clues as to the error or issue.  The following steps are necessary after the setup has completed.

1) Open a new terminal or source the bashrc file in the existing one by executing: source ~/.bashrc
2) cd /home/USER/foam
3) execute: cp -p $FOAM_RUN
4) execute: run
5) cp $FOAM_TUTORIALS .    (note the dot after TUTORIALS)
6) cd tutorials/incompressible/cavity/icoFoam
7) execute: ./Allclean
8) execute: ./Allrun

**Comment by wrighematthey** [comment]
The initial install scripts run okay but the cp -p $FOAM_RUN command brings up an error.  When I try to change to the $FOAM_RUN directory, it is pointing to home/fastuser/foam/fastuser-3.1/run which does not exist (user account is fastuser).  Within the foam directory there are only foam-extend-3.1 and site directories.

[fastfcExtendSP.log.txt](https://github.com/fastSimulations/fastExtendSetup/files/57931/fastfcExtendSP.log.txt)
[fastfcOSSetup.log.txt](https://github.com/fastSimulations/fastExtendSetup/files/57932/fastfcOSSetup.log.txt)

**Comment by wrighematthey** [comment]
I have now changed the cp -p $FOAM_RUN to mkdir -p $FOAM_RUN and this seems to be working.  I'll try building the fastfc code and will see if that also runs.  I have tried adding the alias line "alias fast='source $WM_PROJECT_USER_DIR/FastFC/etc/bashrc' but when I start a new terminal and type fast, it brings up an error as the directory /home/fsatuser/foam/fastuser-3.1/FastFC/etc/bashrc does not exist yet.  This might suggest that either the $WM_PROJECT_USER_DIR is pointing to the wrong place or that the fast code has not built properly
- All working now after cloning the FastFC repository and then building.  Just got confused between the different repositories as I forgot the order in which they needed to be cloned / built in.

Thanks,

Ed

**Comment by fastSimulations** [comment]
Hi Ed,

Good catch on the creation of $FOAM_RUN, the command should have been "mkdir" not "cp"

Glad to know its up and running, I will close out the issue.

There are some pending updates for the fast repository that will come in over the next couple of weeks now that my leap installation has stabilized.

David
